ALTER TYPE "RoleName" ADD VALUE IF NOT EXISTS 'PLANT_MANAGER';
ALTER TYPE "RoleName" ADD VALUE IF NOT EXISTS 'SERVICE_CENTRE_STAFF';
ALTER TYPE "RoleName" ADD VALUE IF NOT EXISTS 'FINANCE_SAP_REVIEWER';
